#------------------------------------------------------------------------------#
# (TITLE TO BE DETERMINED)
# Municipal Characteristics Data wrangling script
# Prepared by:
# Andre Assumpcao
# aassumpcao@unc.edu
#------------------------------------------------------------------------------#
rm(list=ls())

#------------------------------------------------------------------------------#
# README:
#
# This second script file wrangles data at the municipal level. What we do here
# is pull information on municipal characteristics to control for in the regres-
# sion analysis. This file should be joined onto the service order database (so.
# data.Rdata) generated by the first script 00-CorruptionDiscretion-ServiceOrder
# Wrangling.R.
#
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
################################### Packages ###################################
#------------------------------------------------------------------------------#
library(tidyverse) # Version 1.2.1
library(haven)     # Version 1.1.1
library(lubridate) # Version 1.7.4
library(readxl)    # Version 1.1.0
library(psych)     # Version 1.8.4
library(magrittr)  # Version 1.5
library(stargazer) # Version 5.2.1
library(lfe)       # Version 2.6-2291
library(cepespR)   # Version 0.1.0

#------------------------------------------------------------------------------#
################################ Data Wrangling ################################
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
########################### Municipal Characteristics ##########################
#------------------------------------------------------------------------------#
### Population
# 1. Total Population
# 2. Urban Population Share
# 3. Female Share

### Education
# 4. Illiteracy rate

### Income
# 5. Income per capita
# 6. Income inequality (GINI)

### Human Development Index (HDI)
# 7. Municipal HDI
# 8. Share of poor population

### Information and access to justice
### Presence of...
# 9...  Judiciary Seat
# 10... AM Radio
# 11... Education Council
# 12... Health Council

### Election Data
# 13. Mayor vote margin
# 14. Reelected mayor?

#------------------------------------------------------------------------------#
################################### Download ###################################
#------------------------------------------------------------------------------#
# All data here comes from the public sources below. Though I have included all
# files in the submission folder, these remain here for replication purposes.
# Download dates: May 21-25, 2018

# # IBGE Censo 2010
# download.file(paste("http://servicodados.ibge.gov.br/Download/Download.ashx?",
#   "u=ftp.ibge.gov.br/Censos/Censo_Demografico_2010/indicadores_sociais_munic",
#   "ipais/Brasil.zip", sep = ""), "Brasil.zip")

# # IBGE GDP per capita
# download.file(paste("http://servicodados.ibge.gov.br/Download/Download.ashx?",
#   "u=ftp.ibge.gov.br/Pib_Municipios/2010/base/base_xlsx.zip", sep = ""),
#   "base_xlsx.zip")

# # IBGE Income inequality
# download.file(paste("http://tabnet.datasus.gov.br/cgi/ibge/censo/bases/ginib",
#   "r.csv", sep = ""), "ginibr.csv")

# # IBGE HDI organized by Atlas Brasil
# download.file(paste("http://www.atlasbrasil.org.br/2013/data/rawData/atlas20",
#   "13_dadosbrutos_pt.xlsx", sep = ""), "atlas2013_dadosbrutos_pt.xlsx")

# # IBGE Municipal Profiles (MUNIC)
# download.file(paste("http://servicodados.ibge.gov.br/Download/Download.ashx?",
#   "u=ftp.ibge.gov.br/Perfil_Municipios/2009/base_MUNIC_2009.zip", sep = ""),
#   "base_MUNIC_2009.zip")

# # TSE 2000 candidate information
# download.file(paste("http://agencia.tse.jus.br/estatistica/sead/odsele/consu",
#   "lta_cand/consulta_cand_2000.zip", sep = ""),
#   "consulta_cand_2000.zip")

# # TSE 2004 candidate information
# download.file(paste("http://agencia.tse.jus.br/estatistica/sead/odsele/consu",
#   "lta_cand/consulta_cand_2004.zip", sep = ""),
#   "consulta_cand_2004.zip")

# # TSE 2008 candidate information
# download.file(paste("http://agencia.tse.jus.br/estatistica/sead/odsele/consu",
#   "lta_cand/consulta_cand_2008.zip", sep = ""),
#   "consulta_cand_2008.zip")


#------------------------------------------------------------------------------#
############################### Load data into R ###############################
#------------------------------------------------------------------------------#
# Population
unzip("Brasil.zip", "tab1.xls")
mun.data <- read_excel("tab1.xls") %>%
  select(X__1, X__4, X__6) %>%
  filter(!is.na(X__1)) %>%
  filter(!is.na(X__4) & !is.na(X__6)) %>%
  transmute(
    ibge.id       = as.double(substr(X__1, 1, 6)), # IBGE id
    mun.urbanpop  = as.double(X__4),               # Urban population share
    mun.femalepop = as.double(X__6),               # Female population share
  )

# Literacy rate
unzip("Brasil.zip", "tab3.xls")
education <- read_excel("tab3.xls") %>%
  select(X__1, X__4) %>%
  filter(!is.na(X__1)) %>%
  filter(!is.na(X__4)) %>%
  transmute(
    ibge.id        = as.double(substr(X__1, 1, 6)), # IBGE id
    mun.illiteracy = as.double(X__4)                # Illiteracy rate
  )

mun.data %<>% full_join(., education)

# Income per capita
unzip("base_xlsx.zip")
income <- read_excel("base_xlsx.xlsx", col_names = F, col_types = "text") %>%
  select(X__4, X__18) %>%
  filter(!is.na(as.double(X__18))) %>%
  transmute(
    ibge.id    = as.double(substr(X__4, 1, 6)), # IBGE id
    mun.income = as.double(X__18)               # Income per capita
  )

mun.data %<>% full_join(., income)

# Income inequality
gini <- read_delim("ginibr.csv", col_names = F, delim = ";") %>%
  select(X1, X4) %>%
  separate(1, c("ibge.id", "mun.name"), 6, remove = T) %>%
  filter(!is.na(X4)) %>%
  slice(2:5566) %>%
  transmute(
    ibge.id  = as.double(ibge.id),                  # IBGE id
    mun.gini = as.double(str_replace(X4, ",", ".")) # Gini Index
  )

mun.data %<>% full_join(., gini)

# Human Development Index and share of poor population
hdi <- read_excel(
  "atlas2013_dadosbrutos_pt.xlsx", col_types = "text", sheet = "MUN 91-00-10"
) %>%
  select(ANO, Codmun6, IDHM, PMPOB) %>%
  filter(ANO == 2010) %>%
  transmute(
    ibge.id  = as.double(Codmun6), # IBGE id
    mun.idhm = as.double(IDHM),    # HDI
    mun.poor = as.double(PMPOB)    # Share of poor population
  )

mun.data %<>% full_join(., hdi)


# Information and access to justice
unzip("base_MUNIC_2009.zip")

### I had to save this file in .xlsx before importing into R

# Presence of AM Radio
radio <- read_excel("base.xlsx", sheet = "Cultura") %>%
  select(A1, A259) %>%
  filter(!is.na(A1)) %>%
  transmute(
    ibge.id = A1,
    mun.radio = ifelse(A259 == "Sim", 1, 0)
  )

# Presence of Education Council
educationcouncil <- read_excel("base.xlsx", sheet = "Educação") %>%
  select(A1, A211) %>%
  filter(!is.na(A1)) %>%
  transmute(
    ibge.id = A1,
    mun.educationcouncil = ifelse(A211 == "Sim", 1, 0)
  )

# Presence of Health Council
healthcouncil <- read_excel("base.xlsx", sheet = "Saúde") %>%
  select(A1, A391) %>%
  filter(!is.na(A1)) %>%
  transmute(
    ibge.id = A1,
    mun.healthcouncil = ifelse(A391 == "Sim", 1, 0)
  )

# Municipality is the seat of the local Judiciary Branch
judiciary <- read_excel("base.xlsx", sheet = "Segurança") %>%
  select(A1, A488) %>%
  filter(!is.na(A1)) %>%
  transmute(
    ibge.id = A1,
    mun.judiciary = ifelse(A488 == "Sim", 1, 0)
  )

# Join them together
mun.data %<>%
  full_join(., radio) %>%
  full_join(., educationcouncil) %>%
  full_join(., healthcouncil) %>%
  full_join(., judiciary)



# TSE results data
# 2000, 2004, 2008 Municipal Elections
elections2000 <- read_excel(
  "Resultados_Eleitorais_2000_vf.xlsx", sheet = "ElecComp2000")
elections2004 <- read_excel(
  "Resultados_Eleitorais_2004_vf.xlsx", sheet = "ElecComp2004")
elections2008 <- read_excel(
  "Resultados_Eleitorais_2008_vf.xlsx", sheet = "ElecComp2008")

mun.election <-
  full_join(elections2000, elections2004, by = c("cod_mun" = "cod_mun")) %>%
  full_join(., elections2008, by = c("cod_mun" = "cod_mun")) %>%
  select(ibge.id = cod_mun, contains("ElecComp")) %>%
  gather(
    contains("ElecComp"),
    key   = "mun.election",
    value = "mun.votemargin"
  ) %>%
  mutate(mun.election = str_remove(mun.election, "ElecComp"))

# Reelection data
reelected2000 <- read_excel("d_reelected_all.xlsx", sheet = "d_reelected2001")
reelected2004 <- read_excel("d_reelected_all.xlsx", sheet = "d_reelected2005")
reelected2008 <- read_excel("d_reelected_all.xlsx", sheet = "d_reelected2009")

# Municipal Reelection
mun.reelection <-
  full_join(reelected2000, reelected2004, by = c("cod_mun" = "cod_mun")) %>%
  full_join(., reelected2008, by = c("cod_mun" = "cod_mun")) %>%
  select(
    ibge.id         = cod_mun,
    d_reelected2000 = d_reelected2001,
    d_reelected2004 = d_reelected2005,
    d_reelected2008 = d_reelected2009
  ) %>%
  gather(
    contains("d_reelected"),
    key = "mun.election",
    value = "mun.reelected"
  ) %>%
  mutate(mun.election = str_remove(mun.election, "d_reelected"))

# Join all
mun.election %<>%
  full_join(
    .,
    mun.reelection,
    by = c("ibge.id" = "ibge.id", "mun.election" = "mun.election")
)

# Remove useless data
rm(
  list = objects(pattern = "education|health|reelect|elections"),
  gini, hdi, judiciary, radio, income
)